### ISSUE TITLE
Use Weblate

### ISSUE THREAD

**Issue by comradekingu** [strongbox-password-safe/babel#114]
Would it be possible to have this use Hosted Weblate?
KeePassDX is already on there, so it would be nice to check up on Strongbox when working on the source strings. :)
Happy to provide a nb_NO translation.

**Comment by strongbox-mark** [comment]
HI there, we're using the CrowdIn platform at the moment and it's working out pretty well. I'm not sure if there's much value having it in 2 locations or moving at this point? nb_NO is just about finished now and should be releasing next week :)

**Comment by comradekingu** [comment]
@strongbox-mark I checked some of those files in the repo. Neither the source nor the translation holds up.
Strongbox has 5 languages with coverage, in 7 month. In comparison, KeepassDX on Hosted has 12, with a lot more partially translated ones. The quality doesn't compare. It was out to lunch, but now it is fixed. It has no serious failing checks in any languages, though admittedly I did clear up 2 XML errors in Romanian just now.

I can't actually work on anything on Crowdin without dual-licensing my work into their closed translation memory. It also does tracking and profiling and sells data about me and my activity to advertisers and data collection agencies. Furthermore it doesn't allow gratis hosting to libre software projects unless they have no source of income. The Crowdin terms and conditions and cookie policy is a bleak read.

**Comment by strongbox-mark** [comment]
Hi @comradekingu 

I have no issue with using Weblate but I have questions about how it will integrate with the current system and how difficult it is to setup.

1) Have you setup Hosted Weblate before? Is there much effort required? Is this something you're willing to do?

2) Is it possible to host the translation as is on CrowdIn and also on Weblate?

3) When you say "I checked some of those files in the repo. Neither the source nor the translation holds up." what are you referring to here? The Norwegian Bokmal translation, if so any specific examples I could discuss with our Norwegian translator?

Cheers,
-Mark

**Comment by comradekingu** [comment]
1. Send a request at https://hosted.weblate.org/hosting/ I don't know what .strings is, but I have seen similar looking strings. I can help out if you add me as an admin once set up. I haven't set up any projects, but I administrate a lot of projects I contribute to. There is a guy working at Weblate that will help you with that sort of thing, and I can help with what I know.
2. Just don't. More potential errors, and no tangible benefit.
3. I refuse to improve the Crowdin TM even just a little bit. Most things will trigger failing language checks when added to Weblate, so you will know.

**Comment by strongbox-mark** [comment]
1. Thanks, I'll send a request and see what they say, then add you as an admin if accepted. Github integration would be great.

2. This is an absolute requirement at least initially. There are 9 languages being actively translated by volunteers and I update the app/source strings regularly as I build out the app. If Weblate turns out to be a better platform then we'd look at transitioning but it needs to work first, not be a problem for my workflow, and not cause issues with a very well functioning current setup.

3. That's fair, I understand your concerns. There wasn't a lot of thought went into using CrowdIn, we did try GitLocalize but it was awful, and hadn't heard of Weblate. 

I'm definitely not asking you to contribute, but you've said there is some problem with the Norwegian translation? Can you elaborate at all on that as it is quite a concern. Our main translator there seems to be quite happy with it. Perhaps you were looking at an old version? 

NB: Strongbox 1.48.4 is available now in Norwegian Bokmal on the App Store if you'd like to verify or pass on any comments.
