### ISSUE TITLE
Populate Hosted Weblate translation project

### ISSUE THREAD

**Issue by comradekingu** [strongbox-password-safe/babel#149]
https://hosted.weblate.org/projects/strongbox/#information is up, but not populated.
I can help if you add https://hosted.weblate.org/user/kingu/ as an admin. :)

**Comment by comradekingu** [comment]
Changed VCS to "GitHub" from "Git", and set push branch to "weblate" for all components and opened them.

I was going to add the Weblate bot, but I think I have to commit something to master to do so

https://github.com/strongbox-password-safe/babel/settings/interaction_limits  Has
> Limit to prior contributorsUsers that have not previously committed to the repository’s master branch will be unable to interact with the repository.

turned on. Can I just change something in the README.md?

https://docs.weblate.org/en/latest/vcs.html#vcs-repos
https://docs.weblate.org/en/latest/admin/continuous.html?highlight=github#pushing-changes-from-weblate
https://docs.weblate.org/en/latest/vcs.html#vcs-reposhttps://docs.weblate.org/en/latest/admin/continuous.html?highlight=github#lazy-commit

are the last part of the documentation (I think) :)

**Comment by strongbox-mark** [comment]
Sure feel free to change the README if it will help :)

**Comment by comradekingu** [comment]
@strongbox-mark 
> For Hosted Weblate there is a dedicated push user registered on GitHub, Bitbucket, Codeberg and GitLab (with username "weblate" named "Weblate push user"). You need to add this user as a collaborator and give it appropriate permission to your repository (read only is okay for cloning, write is required for pushing).

**Comment by strongbox-mark** [comment]
OK, I've added weblate user now with write permissions.

**Comment by comradekingu** [comment]
https://github.com/strongbox-password-safe/babel/pull/154 and it works :)
Down with Crowdin. Long live Weblate.

**Comment by strongbox-mark** [comment]
That's great news...  Congratulations! Well done, and thanks for all your help... 

I would like to try to keep some kind of organisation in place on who is doing what translation. I have a few very dedicated and diligent translators for different languages and they've worked hard on what they've done already. I believe they are owed some kind of seniority/ownership of the translation process for their particular languages.

As you will probably know there are subjective choices made in the translations and not all translators will agree on terminology, formality and other issues so I would like to avoid multiple people stepping on each others toes and/or overwriting each others changes on a per language basis across the two systems. That means choosing and sticking with a platform for each current language... New languages can be done on Weblate (unless problems arise, we're still in trial mode).

An example presents itself in #154. The current Norwegian Bokmål translator is quite inactive (has stepped away from active translation) and so your contributions are extremely welcome! Thank you so much btw! 👍 

However, this isn't the case for Russian which has a very committed and dedicated translator who has done a really great job on Russian. I see in #154 a couple of commits with changes to Russian from KovalevArtem . While this could actually be a good thing, I'd certainly like to introduce these two translators and have them agree on a strategy for translation, and choose a platform together and come to some sort of working modus operandi.

I would like to start trying out Weblate now, with a view to moving to it as a possible default translation platform, but that will be a soft and slow transition where I would ask new language translators to use Weblate, and I will also contact current translators and see if they're interested in the shift over to Weblate instead of CrowdIn because it offers better terms/privacy etc. At the end of the day though, that will be a decision for those individual translators because I want to keep them happy and comfortable...

I hope that sounds ok to you. To that end is it possible to ask contributors on Weblate to contact me so that I can keep some kind of order on the process? Is there a way to do that?

**Comment by comradekingu** [comment]
@strongbox-mark I thought I was the nb_NO translator. Happy to help as long as my changes don't end up on Crowdin.

Anyhow https://hosted.weblate.org/projects/strongbox/strings/#alerts is a problem. Is it because the PR is sitting open for longer than no changes are made from elsewhere?

Translators can argue improvements in the comment section on Weblate.

Nobody is interested in Crowdin, because it is moronic on every level. There are never any complaints moving things over from it.
You can selectively give people review rights, and ask for people to contact you in the Weblate translation info section or announcements to do so.

**Comment by strongbox-mark** [comment]
Hi @comradekingu - I'm afraid at the moment I just don't have the resources to manage this transition or 2 separate systems. 

The current system, with all its faults, works really well for us and so for the moment we will keep it as primary. I understand your concerns and understand you don't want to contribute to the project under its current configuration. Appreciate your contributions so far, and we'll keep Weblate on the backburner.
